# Site settings
title:          Code with Lucky Father & Brave Papa
description:    "Lucky Father & Brave Papa's Blog"
baseurl:        ""
url:            "https://LuckyBrave.github.io"

# Google Analytics
google_analytics: G-EHX6G14MNT

# Author
authors:
  finn:
    name:         youth6erry
    url:          https://github.com/youth6erry
    email:
  ahn:
    name:         KUAHN
    url:          https://www.kuahn.com
    email:        z@kuahn.com

# Build settings
markdown:       kramdown
include:
  - _pages

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
#  - jemoji

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       5

# Excludes
exclude: [ Gemfile, Gemfile.lock, tale.gemspec ]

# Disqus (Set to your disqus id)
disqus:         jekyll-tale

# with local
#theme:      tale